### ISSUE TITLE
egui_gauge dependency on 0.25.0, upgrade to 0.26.0

### ISSUE THREAD

**Issue by vortex314** [bobbobbio/egui_gauge#1]
Is it possible to upgrade the crate to the dependency egui 0.26.0 ? See my issue : https://github.com/emilk/egui/discussions/3991

Thanks again for your interesting crate , my project : https://github.com/vortex314/egui-dashboard

Hope you can help.

**Comment by vortex314** [comment]
Upgrade pull request has been merged. Thanks !

**Comment by bobbobbio** [comment]
I've published version 0.1.4 with the changes
